### ISSUE TITLE
Release 1.4.0

### ISSUE THREAD

**Issue by acrobat** [eternicode/bootstrap-datepicker#1200]
This release will include long open features and will continue to clean up the huge list of open issues and pull requests.

## Feature
- #1074 - implemented beforeShowMonth option (Fixes: #807)
- #842 - Added option to disable touch keyboard input (Fixes: #787)
- #722 - All datepicker methods are chainable
- #515 - Added a datesDisable option 
- #802 - Added option to prevent date picker to show when input field receives focus 
- #918 - adding option to define the container the datepicker will be appended to (Fixes: #384, #896) 
- #1227 - Backported some placement fixes for the container option (Fixes: #325, #384, #410)
- #893 - Option default view date 
- #883 - Add toggleActive option 
- #1245 - Added clear method
- #1205 - Added version property to datepicker object
- #1280 - Added option to not show datepicker on readonly field (Fixes: #1231)

## Bugfix
- #670 - Removed blank space before the previous button when calendarWeeks is true; 
- #843 - Fixed date deselection with single date picker (Fixes: #775, #813, #816)
- #832 - Added case-neutral matching for text months
- #887 - Changed input-daterange to full width for bs3
- #1192 - Fix placement for RTL languages (Fixed: #1079)
- #1036 - fix for range picker when next date is before previous date (Fixes: #914, #821, #1031, #1122)
- #1212 - Fix for moving box on first selection  
- #1136 - Do not show datepicker for readonly inputs 
- #1213 - Fix getUTCDate when datepicker has no selected date (Fixed: #923)
- #754 - Only a linked today button should trigger the changeDate event
- #1165 - Fixed bug with keyboard navigation when startdate/enddate was defined
- #546 - Right align calendar on right window edge conflict 
- #826 - On "ENTER" keydown on picker, prevent the closest form to be submitted too
- #853 - fixed bower.json twitte bootstrap dependency 
- #961 - Replaced named entities with decimal entities 
- #1117 - assigning plugin to a local variable to fix bug in noConflict
 
## Repository
- Added empty ignore option in `bower.json`. Fixes: #1199
- #1195 - Added .editorconfig
- #1185 Reworked grunt tasks

## Translations
- #1024 - Fix translation of French months 
- #1178 - Update cambodia translations 
- #1230 - added clear and weekStart to turkish translation
- #1240 - Days/months should start lowercase in dutch
- #1239 - Month/daynames should be lowercase in french
- #1271 - Add 'clear' and 'format' to Ukrainian locale
- #1276 - Added Montenegrin locale

## Docs
- #1232 - added example for inputs option
- #699 - added missing documentation for embedded mode 
- #1287 - Add additional documentaion to update method

## Todo

- [x] Merge new demo features after release: #1206, #1220, #1281
- [x] add docs for [these issues  ](https://github.com/eternicode/bootstrap-datepicker/issues?q=milestone%3A1.4.0++label%3Adocs-needed+)
- [x] add examples to the sandbox page for [these issues](https://github.com/eternicode/bootstrap-datepicker/issues?q=is%3Aopen+label%3Aexample-needed+milestone%3A1.4.0+)
- [x] Publish package on npm (#1191)
- [x] Update download link on sandbox page
- [x] Create 1.4 branch for bugfixing and use master for the next feature release
